BACKGROUND_FILE_PATH: "../data/background/chess"
SAMPLE_FILES_PATH: "../data/GermanFlag"
OUTPUT_PATH: "../../train"
BACKGROUND_COLOR : 255
BACKGROUND_THRESH : 100
MAX_X_ANGLE: 30
MAX_Y_ANGLE: 30
MAX_Z_ANGLE: 30
MAX_AFFINE_ANGLE: 360
AFFINE_ROT_PROB: 0.6
PERSP_TRANS_PROB: 0.05
GAUSS_NOISE_PROB: 0.05
MEDIAN_NOISE_PROB: 0.05
SHARPEN_PROB: 0.3
OUTPUT_PER_SAMPLE: 250
SCALING_PROB: 0.7
BRIGHTNESS_PROB: 0.5
